spring:
  profiles: production
  data:
    mongodb:
      database: shrinker_db
#      username:
#      password:
      host: 0.0.0.0
      port: 27017

kafka:
  groupId: shrinker
  bootstrap: localhost:9092,localhost:9093,localhost:9094

server:
  port: 12345

