spring:
  profiles: production
  data:
    mongodb:
      database: shrinker_db
#      username:
#      password:
      host: mongodb
      port: 27017

kafka:
  groupId: shrinker
  bootstrap: kafka-1:9092

server:
  port: 12345

