server:
  port: 12345

spring:
  data:
    mongodb:
      database: shrinker_db
#      username:
#      password:
      host: localhost
      port: 27017


kafka:
  groupId: shrinker
  bootstrap: localhost:9092